[package]
name = "rfm9x"
version = "0.1.0"
authors = ["Tommy van der Vorst <tommy@pixelspark.nl>"]
edition = "2018"
description = "RFM9x LoRa/FSK transceiver driver for Raspberry Pi in native Rust"
license = "MIT"
categories = ["embedded", "hardware-support"]
keywords = ["iot","raspberry", "rpi", "pi", "lora", "lorawan"]
repository = "https://git.pixelspark.nl/pixelspark/rfm9x"

[dependencies]
bitflags = "1.2.1"
rppal = "0.11.3"
rand = "0.7.2"